# Nome da Aplicação
spring.application.name=orbifreight

# Configurações de Conexão com o Oracle FIAP
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=user
spring.datasource.password=senha
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true