spring.application.name=orbifreight

# Configurações do Banco de Dados H2 (Em Memória)
spring.datasource.url=jdbc:h2:mem:orbifreightdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto do H2 e geração automática de tabelas
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Logs de SQL no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilitar o console do H2 no navegador (opcional para testes)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console